name: Golang Coverage
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'golang/**'
  push:
    branches:
      - master
jobs:
  calculate-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Golang ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Generate coverage report
        working-directory: ./golang
        run: go test -coverprofile coverage.out
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./golang/coverage.out
          flags: golang
          fail_ci_if_error: true
          verbose: true